### ISSUE TITLE
Is there any workaround for SBC devices?

### ISSUE THREAD

**Issue by Itz-Broken-xd** [R0rt1z2/lkpatcher#1]
Device : Oppo f15
OS : ColorOs 11.1 (based on a11)

Lk image : [lk.bin](https://xfl.jp/YbWmei)
Expbd : [expdb.bin](https://xfl.jp/RUiduM)

Note : the above lk image is booting(stock one) 
But it still shows image auth fail in expdb.

In expbd: 
`[PART] load "lk" from 0x000000002AD00200 (dev) to 0x57000000 (mem) [SUCCESS] 
[PART] load speed: 254620KB/s, 2346580 bytes, 9ms 
[PART] img vfy...[SBC] img auth fail(0x101004) 
fail(0x101004)`

But my device boots successfully (stock lk image but still verify fail)

Avb is patched by magisk. 

Btw my device has two bootloader partitions `lk` and `lk2`.

Any fix?

Btw what is `SBC` or what makes a device `SBC`.

**Comment by R0rt1z2** [comment]
Can you please send the tool's output?

**Comment by Itz-Broken-xd** [comment]
I used online patcher and it worked fine(it showed no error). But when flashed it wont boot the device

**Comment by CE1CECL** [comment]
@n0t-Human Just want to make sure (sorry for old bump) you did this in mtkclient:
```
python mtk.py da seccfg unlock
```
This issue only happens to me when its locked on TCL 5102L (A30)

**Comment by n0t-Human** [comment]
@CE1CECL 

I tried unlocking using mtkclient but it showed some error. So I unlocked it using Meadiatek Easy Tool. 

Ss:
![IMG_20241016_225150_203.jpg](https://github.com/user-attachments/assets/8d7c81e4-c936-4229-a438-dd178e90f0c5)

**Comment by n0t-Human** [comment]
> Don't advertise shitty MTKClient rebrands, please.

Sorry, I didn't mean to. I provided the details if he could find any workaround. I'm not sponsored by those rebrands.🥲
