### ISSUE TITLE
There is a BL Lock problem about HarmonyOS. 

### ISSUE THREAD

**Issue by Ceyase** [R0rt1z2/lkpatcher#11]
I have unlocked seccfg, but I did not successfully unlock Bootloader. I'm sure this is because Huawei modified lk, maybe not. I tried using Ghidra to analyze this file, but I didn't get any results. I need to use Magisk, so I just need to skip the verification - if possible.
Before receiving your response, I will do my best to decode this lk.bin. By the way, your blog and online tool website are both damaged. 

Some information may be useful:
[lk.zip](https://github.com/R0rt1z2/lkpatcher/files/14866254/lk.zip)
![1712233577213](https://github.com/R0rt1z2/lkpatcher/assets/95260108/444d5202-598d-44ad-a0ec-f5eae92177e7)

```shell
[Ceyase@CeyaseArch ~]$ adb reboot bootloader
[Ceyase@CeyaseArch ~]$ fastboot oem unlock
(bootloader) cmd is invalid
FAILED (remote: 'CMD_OEM FAILED!!')
fastboot: error: Command failed
[Ceyase@CeyaseArch ~]$ fastboot boot /home/Ceyase/Desktop/mtkclient/honor_backup/recovery.bin 
Sending 'boot.img' (46080 KB)                      OKAY [  1.141s]
Booting                                            FAILED (remote: 'Command not allowed')
fastboot: error: Command failed
[Ceyase@CeyaseArch ~]$ fastboot getvar all
getvar:all                                         FAILED (remote: 'Command not allowed')
Finished. Total time: 0.000s
[Ceyase@CeyaseArch ~]$ 

```

**Comment by Ceyase** [comment]
bro, you don't need to solve this problem anymore. Because this phone is already broken - completely. I accidentally dropped this phone from upstairs, so ...now the screen is completely useless

**Comment by R0rt1z2** [comment]
lol
