### ISSUE TITLE
Custom patch for Oppo A9 (mt6771v)

### ISSUE THREAD

**Issue by toolingaround** [R0rt1z2/lkpatcher#12]
Attached is lk.img extracted with mtkclient from OPPO A9, 2 patches seem to fail:
```
[lkpatcher.patcher] [WARNING] [2024-04-25 21:42:11] Skipping invalid needle 2de9f04fadf5ac5d.
[lkpatcher.patcher] [WARNING] [2024-04-25 21:42:11] Skipping invalid needle 30b583b002ab0022.
```
[lk.img](https://files.catbox.moe/11noso.img)

**Comment by R0rt1z2** [comment]
The first error is normal, `f0b5adf5925d` was used in your case. The second one is the patch for dm-verity error. I would have to RE your LK to find out the correct sequence, but I've been very busy lately.
