### ISSUE TITLE
Cannot reboot to fastbootd mode

### ISSUE THREAD

**Issue by fayaz-modz** [R0rt1z2/lkpatcher#15]
model: mt6768

I'm stuck in bootloader mode, (i am able to goto recovery but cannot go to fastbootd mode) when i type fastboot reboot fastboot, it reboots to bootloader only

**Comment by R0rt1z2** [comment]
I'm sorry, but what does this have to do with my tool? Have you patched your LK with it? I need more details, such as the phone model, the brand, and the Android version.

**Comment by fayaz-modz** [comment]
Yes, I have patched my lk_a file. I'm able to boot to fastboot mode. When I type fastboot devices, it says 'fastboot' not bootloader. And I'm trying to boot to fastbootd but I come back to the same mode.

My device is realme c55.

**Comment by R0rt1z2** [comment]
I believe this is unrelated to lkpatcher so I'm just gonna close this issue.
