### ISSUE TITLE
Why is the file in my phone named lk.bin instead of lk.img?

### ISSUE THREAD

**Issue by TrWelldone** [R0rt1z2/lkpatcher#17]

**Comment by TrWelldone** [comment]
My phone is oppo pam00, Android 10,f27

**Comment by halal-beef** [comment]
they're the sane file different extensions hehe

**Comment by TrWelldone** [comment]
So, i just need to change the file extension from .bin to .img,right?

**Comment by TrWelldone** [comment]
I have uploaded the lk.img to this web,but this web seen to fail.https://lkpatcher.r0rt1z2.com/
It keeps showing 'processing'

**Comment by R0rt1z2** [comment]
The website is currently broken, and I need to fix it (when I have some free time). Yes, the extension does NOT matter. For now, please use the CLI tool.
