### ISSUE TITLE
Web server is down ?

### ISSUE THREAD

**Issue by BASHEER-A** [R0rt1z2/lkpatcher#19]
Hi, website not work from yesterday 
https://lkpatcher.r0rt1z2.com
![image](https://github.com/R0rt1z2/lkpatcher/assets/25770575/ada5807b-2f07-4b19-be56-c4ab1407b732)

**Comment by R0rt1z2** [comment]
The website has been inactive for a while, so please stop opening issues about it. I will fix it when I have some free time.
