### ISSUE TITLE
TCL 5102

### ISSUE THREAD

**Issue by CE1CECL** [R0rt1z2/lkpatcher#9]
The TCL A30 doesn't have any options in stock recovery other than to reset the device, and there isn't a fastboot mode I can get out of it. Vol+ + Pwr goes to recovery, Vol- + Pwr, nothing but boot normal. Any help possible?

**Comment by R0rt1z2** [comment]
Send me the LK image and I will take a look.

**Comment by CE1CECL** [comment]
[5102L.zip](https://github.com/R0rt1z2/lkpatcher/files/14501470/5102L.zip)

**Comment by CE1CECL** [comment]
[Uploading expdb.txt…]()

**Comment by CE1CECL** [comment]
[expdb.txt](https://github.com/R0rt1z2/lkpatcher/files/14501839/expdb.txt)

**Comment by CE1CECL** [comment]
> Assuming you have checked that you can boot unsigned LK images, you can [try this one](https://github.com/R0rt1z2/lkpatcher/files/14501825/lk-patched.zip). It also includes an script to force the boot mode. Try using `python3 handshake2.py FASTBOOT` and connecting the device powered off (the script waits for a device in preloader mode).

```
# python3 handshake2.py FASTBOOT
Waiting for preloader...
Found port = /dev/ttyACM0
Traceback (most recent call last):
  File "/root/handshake2.py", line 96, in <module>
    handshake()
  File "/root/handshake2.py", line 57, in handshake
    c = dev.read()
  File "/usr/local/lib/python3.10/dist-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```
and it still boots to recovery

**Comment by R0rt1z2** [comment]
> > Assuming you have checked that you can boot unsigned LK images, you can [try this one](https://github.com/R0rt1z2/lkpatcher/files/14501825/lk-patched.zip). It also includes an script to force the boot mode. Try using `python3 handshake2.py FASTBOOT` and connecting the device powered off (the script waits for a device in preloader mode).
> 
> ```
> # python3 handshake2.py FASTBOOT
> Waiting for preloader...
> Found port = /dev/ttyACM0
> Traceback (most recent call last):
>   File "/root/handshake2.py", line 96, in <module>
>     handshake()
>   File "/root/handshake2.py", line 57, in handshake
>     c = dev.read()
>   File "/usr/local/lib/python3.10/dist-packages/serial/serialposix.py", line 595, in read
>     raise SerialException(
> serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
> ```
> 
> and it still boots to recovery

That's really weird, I forced boot mode to be 99 regardless of the key combo. I guess it won't be as easy as that, then. I can try to port my LK payload to your device but that might take a bit of effort and time. I will do it tomorrow. For quicker and more convenient testing, feel free to reach out to me on Telegram at: [t.me/R0rt1z2](https://t.me/R0rt1z2) (if you don't have, then let's just continue here).
